// ---------------------------------------------------------------------------
// atlas_ui.h - the in-game Collection Atlas window.
//
// Six pages - Appearances, Mounts, Pets, Gliders, Trinkets, Weapons - each a
// grid of every item that exists in that category, owned ones in colour with
// a rarity border, missing ones dimmed. Hover shows name, rarity, level (for
// owned gear), description and how to acquire. F8 toggles, the title bar
// drags, Escape closes; position and tab persist across sessions.
//
// Static data comes from farever-atlas.tsv + farever-atlas-icons.dds next to
// the game executable, generated by tools/gen-atlas.mjs from the game's own
// CastleDB and portrait art. Ownership comes from the live reader plus the
// farever-inventory-<character>.json files of characters not logged in.
// ---------------------------------------------------------------------------
#pragma once

#include "hl_reader.h"

namespace fmk {

// Worker thread, after overlay_ready(): loads TSV, icon atlas, saved layout.
bool atlas_ui_init();

// Worker thread: fresh reader output. Rebuilds the ownership snapshot the
// draw side reads.
void atlas_ui_update(const Collection& c, const Inventories& inv);

// Worker thread, about once a second: persists layout when it changed.
void atlas_ui_tick();

// Render thread: the overlay draw callback.
void atlas_ui_draw(float w, float h);

}  // namespace fmk
