// ---------------------------------------------------------------------------
// atlas_ui.h - the in-game Collection Atlas window.
//
// Six pages - Appearances, Mounts, Pets, Gliders, Trinkets, Weapons - each a
// grid of every item that exists in that category, owned ones in colour with
// a rarity border, missing ones dimmed. Hover shows name, rarity, level (for
// owned gear), description and how to acquire. F8 toggles, the title bar
// drags, Escape closes; position and tab persist across sessions.
//
// Static data comes from farever-atlas.tsv + farever-atlas-icons.dds next to
// the game executable, generated by tools/gen-atlas.mjs from the game's own
// CastleDB and portrait art. Ownership comes from the live reader plus the
// farever-inventory-<character>.json files of characters not logged in.
// ---------------------------------------------------------------------------
#pragma once

#include <string>
#include <utility>
#include <vector>

#include "hl_reader.h"
#include "overlay.h"

namespace fmk {

// Worker thread, after overlay_ready(): loads TSV, icon atlas, saved layout.
bool atlas_ui_init();

// Worker thread: fresh reader output. Rebuilds the ownership snapshot the
// draw side reads. `unit_progress` is the codex: unit id -> the count the
// game tracks for it, absent meaning never encountered.
void atlas_ui_update(const Collection& c, const Inventories& inv,
                     const std::vector<UnitProgress>& unit_progress,
                     const std::vector<JobState>& jobs);

// Pose thread: whether a character is actually in the world. Going false
// (main menu, logout, character select) drops the ownership snapshot and
// hides the window, so nothing from the last session lingers on screen.
void atlas_ui_set_in_world(bool in_world);

// Worker thread, about once a second: persists layout when it changed.
void atlas_ui_tick();

// Render thread: the overlay draw callback.
void atlas_ui_draw(float w, float h);

// --- shared with other mods on this host ------------------------------------
//
// The atlas owns the generated item database and the icon texture. Anything
// else with an item id - the Recent Loots feed, for one - wants the same
// three things about it, and duplicating the TSV load to get them would put
// a second copy of 1547 entries in memory to say "Copper Ore" instead of
// "CopperOre".

struct AtlasItemInfo {
    std::string name;      // the game's own display name
    int rarity = 0;        // 0..4, common..legendary
    int icon = -1;         // cell in the icon atlas, -1 = none
};

// Searches every page for the id. False when the atlas has not loaded yet or
// the id is not one it knows.
bool atlas_ui_lookup(const std::string& id, AtlasItemInfo* out);

// Draws one icon cell at any size. Silently draws nothing when `icon` is -1
// or the atlas texture failed to load.
void atlas_ui_draw_icon(int icon, float x, float y, float size, float alpha);

// The colour the atlas paints a rarity, so borders agree across mods.
Color atlas_ui_rarity_color(int rarity);

}  // namespace fmk
