// GENERATED by tools/gen-offsets.mjs - do not edit.
//
// Field offsets read out of Farever's HashLink bytecode type table and
// laid out with HashLink's own hl_get_obj_rt algorithm. Regenerate after a
// game patch:  node tools/gen-offsets.mjs
#pragma once

#include <stdint.h>

// SHA-256 of the hlboot.dat these offsets came from. The reader must refuse
// to walk pointers when the running game does not match.
#define FMK_BUILD_SHA256 "7c3ca4dd765b50972b0eb524f82f9943a1d24d9ea52cbba97c7f87d5d840e7a0"

namespace fmk {
namespace off {

// ent.Hero  (sizeof=1648, extends ent.Unit)
namespace ent_Hero {
    constexpr uint32_t SIZEOF = 1648;
    constexpr uint32_t player = 0x4b8;  // OBJ : st.Player
    constexpr uint32_t lockedTarget = 0x4d0;  // I64
    constexpr uint32_t autoTarget = 0x4d8;  // I64
    constexpr uint32_t weaponInHand = 0x538;  // OBJ : st.item.Weapon
    constexpr uint32_t loadout = 0x4c8;  // OBJ : st.Loadout
}  // namespace ent_Hero

// ent.Unit  (sizeof=1208, extends ent.GameObject)
namespace ent_Unit {
    constexpr uint32_t SIZEOF = 1208;
    constexpr uint32_t isInCombat = 0x2a8;  // BOOL
    constexpr uint32_t instigatedStatuses = 0x1f0;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t skin = 0x3dc;  // I32
}  // namespace ent_Unit

// ent.GameObject  (sizeof=592, extends ent.Entity)
namespace ent_GameObject {
    constexpr uint32_t SIZEOF = 592;
    constexpr uint32_t posx = 0xb0;  // F64
    constexpr uint32_t posy = 0xb8;  // F64
    constexpr uint32_t posz = 0xc0;  // F64
    constexpr uint32_t rotationZ = 0xc8;  // F64
}  // namespace ent_GameObject

// GameApp  (sizeof=320, extends App)
namespace GameApp {
    constexpr uint32_t SIZEOF = 320;
    constexpr uint32_t gameCamera = 0xb0;  // OBJ : client.GameCamera
    constexpr uint32_t camera = 0xa8;  // OBJ : client.BaseCamera
    constexpr uint32_t hero = 0xd0;  // OBJ : ent.Hero
    constexpr uint32_t world = 0x98;  // OBJ : world.World
}  // namespace GameApp

// client.BaseCamera  (sizeof=304, extends h3d.scene.Object)
namespace client_BaseCamera {
    constexpr uint32_t SIZEOF = 304;
    constexpr uint32_t direction = 0xd0;  // F64
    constexpr uint32_t curDirection = 0x100;  // F64
    constexpr uint32_t pitch = 0xd8;  // F64
    constexpr uint32_t curPitch = 0xf8;  // F64
    constexpr uint32_t curDistance = 0x108;  // F64
    constexpr uint32_t enabled = 0xe8;  // BOOL
    constexpr uint32_t scene = 0x118;  // OBJ : h3d.scene.Scene
}  // namespace client_BaseCamera

// h3d.scene.Scene  (sizeof=288, extends h3d.scene.Object)
namespace h3d_scene_Scene {
    constexpr uint32_t SIZEOF = 288;
    constexpr uint32_t camera = 0xa0;  // OBJ : h3d.Camera
}  // namespace h3d_scene_Scene

// h3d.Camera  (sizeof=204)
namespace h3d_Camera {
    constexpr uint32_t SIZEOF = 204;
    constexpr uint32_t pos = 0x58;  // OBJ : h3d.VectorImpl
    constexpr uint32_t target = 0x68;  // OBJ : h3d.VectorImpl
}  // namespace h3d_Camera

// h3d.VectorImpl  (sizeof=32)
namespace h3d_VectorImpl {
    constexpr uint32_t SIZEOF = 32;
    constexpr uint32_t x = 0x8;  // F64
    constexpr uint32_t y = 0x10;  // F64
    constexpr uint32_t z = 0x18;  // F64
}  // namespace h3d_VectorImpl

// st.Player  (sizeof=385, extends st.State)
namespace st_Player {
    constexpr uint32_t SIZEOF = 385;
    constexpr uint32_t accountProgress = 0xe0;  // OBJ : st.player.AccountProgress
    constexpr uint32_t progress = 0xf0;  // OBJ : st.player.Progress
    constexpr uint32_t name = 0xc0;  // OBJ : String
}  // namespace st_Player

// st.player.AccountProgress  (sizeof=208, extends st.DBState)
namespace st_player_AccountProgress {
    constexpr uint32_t SIZEOF = 208;
    constexpr uint32_t collection = 0xa8;  // OBJ : st.player.Collection
    constexpr uint32_t bank = 0xb8;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t bankEquipment = 0xc0;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t bankNbSlots = 0xc8;  // I32
}  // namespace st_player_AccountProgress

// st.player.Collection  (sizeof=168, extends st.DBBaseState)
namespace st_player_Collection {
    constexpr uint32_t SIZEOF = 168;
    constexpr uint32_t mounts = 0x80;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t gliders = 0x78;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t pets = 0xa0;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t gears = 0x98;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t toys = 0x88;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t emotes = 0x90;  // OBJ : hxbit.ArrayProxyData
}  // namespace st_player_Collection

// hxbit.ArrayProxyData  (sizeof=48, extends hxbit.BaseProxy)
namespace hxbit_ArrayProxyData {
    constexpr uint32_t SIZEOF = 48;
    constexpr uint32_t array = 0x28;  // OBJ : hl.types.ArrayDyn
}  // namespace hxbit_ArrayProxyData

// st.Loadout  (sizeof=208, extends st.DBBaseState)
namespace st_Loadout {
    constexpr uint32_t SIZEOF = 208;
    constexpr uint32_t equipment = 0x78;  // OBJ : st.Equipment
    constexpr uint32_t appearance = 0x80;  // OBJ : st.Inventory
    constexpr uint32_t inventory = 0x88;  // OBJ : st.Inventory
}  // namespace st_Loadout

// st.Inventory  (sizeof=160, extends st.DBBaseState)
namespace st_Inventory {
    constexpr uint32_t SIZEOF = 160;
    constexpr uint32_t content = 0x78;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t baseSize = 0x80;  // I32
    constexpr uint32_t addSize = 0x84;  // I32
}  // namespace st_Inventory

// st.item.Gear  (sizeof=160, extends st.Item)
namespace st_item_Gear {
    constexpr uint32_t SIZEOF = 160;
    constexpr uint32_t kind = 0x70;  // OBJ : String
    constexpr uint32_t level = 0x90;  // I32
    constexpr uint32_t upgradeLevel = 0x94;  // I32
    constexpr uint32_t slots = 0x98;  // OBJ : hxbit.ArrayProxyData
}  // namespace st_item_Gear

// st.item.Weapon  (sizeof=176, extends st.item.Gear)
namespace st_item_Weapon {
    constexpr uint32_t SIZEOF = 176;
    constexpr uint32_t rarity = 0xa0;  // OBJ : String
}  // namespace st_item_Weapon

// hl.types.ArrayDyn  (sizeof=17, extends hl.types.ArrayAccess)
namespace hl_types_ArrayDyn {
    constexpr uint32_t SIZEOF = 17;
    constexpr uint32_t array = 0x8;  // OBJ : hl.types.ArrayBase
}  // namespace hl_types_ArrayDyn

// hl.types.ArrayObj  (sizeof=24, extends hl.types.ArrayBase)
namespace hl_types_ArrayObj {
    constexpr uint32_t SIZEOF = 24;
    constexpr uint32_t length = 0x8;  // I32
    constexpr uint32_t array = 0x10;  // ARRAY
}  // namespace hl_types_ArrayObj

// hl.types.ArrayBase  (sizeof=12, extends hl.types.ArrayAccess)
namespace hl_types_ArrayBase {
    constexpr uint32_t SIZEOF = 12;
    constexpr uint32_t length = 0x8;  // I32
}  // namespace hl_types_ArrayBase

// String  (sizeof=20)
namespace String {
    constexpr uint32_t SIZEOF = 20;
    constexpr uint32_t bytes = 0x8;  // BYTES
    constexpr uint32_t length = 0x10;  // I32
}  // namespace String

}  // namespace off
}  // namespace fmk
