// GENERATED by tools/gen-offsets.mjs - do not edit.
//
// Field offsets read out of Farever's HashLink bytecode type table and
// laid out with HashLink's own hl_get_obj_rt algorithm. Regenerate after a
// game patch:  node tools/gen-offsets.mjs
#pragma once

#include <stdint.h>

// SHA-256 of the hlboot.dat these offsets came from. The reader must refuse
// to walk pointers when the running game does not match.
#define FMK_BUILD_SHA256 "7c3ca4dd765b50972b0eb524f82f9943a1d24d9ea52cbba97c7f87d5d840e7a0"

namespace fmk {
namespace off {

// ent.Hero  (sizeof=1648, extends ent.Unit)
namespace ent_Hero {
    constexpr uint32_t SIZEOF = 1648;
    constexpr uint32_t player = 0x4b8;  // OBJ : st.Player
    constexpr uint32_t lockedTarget = 0x4d0;  // I64
    constexpr uint32_t autoTarget = 0x4d8;  // I64
    constexpr uint32_t weaponInHand = 0x538;  // OBJ : st.item.Weapon
    constexpr uint32_t loadout = 0x4c8;  // OBJ : st.Loadout
}  // namespace ent_Hero

// ent.Unit  (sizeof=1208, extends ent.GameObject)
namespace ent_Unit {
    constexpr uint32_t SIZEOF = 1208;
    constexpr uint32_t isInCombat = 0x2a8;  // BOOL
    constexpr uint32_t instigatedStatuses = 0x1f0;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t skin = 0x3dc;  // I32
}  // namespace ent_Unit

// st.Player  (sizeof=385, extends st.State)
namespace st_Player {
    constexpr uint32_t SIZEOF = 385;
    constexpr uint32_t accountProgress = 0xe0;  // OBJ : st.player.AccountProgress
    constexpr uint32_t progress = 0xf0;  // OBJ : st.player.Progress
}  // namespace st_Player

// st.player.AccountProgress  (sizeof=208, extends st.DBState)
namespace st_player_AccountProgress {
    constexpr uint32_t SIZEOF = 208;
    constexpr uint32_t collection = 0xa8;  // OBJ : st.player.Collection
    constexpr uint32_t bank = 0xb8;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t bankEquipment = 0xc0;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t bankNbSlots = 0xc8;  // I32
}  // namespace st_player_AccountProgress

// st.player.Collection  (sizeof=168, extends st.DBBaseState)
namespace st_player_Collection {
    constexpr uint32_t SIZEOF = 168;
    constexpr uint32_t mounts = 0x80;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t gliders = 0x78;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t pets = 0xa0;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t gears = 0x98;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t toys = 0x88;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t emotes = 0x90;  // OBJ : hxbit.ArrayProxyData
}  // namespace st_player_Collection

// hxbit.ArrayProxyData  (sizeof=48, extends hxbit.BaseProxy)
namespace hxbit_ArrayProxyData {
    constexpr uint32_t SIZEOF = 48;
    constexpr uint32_t array = 0x28;  // OBJ : hl.types.ArrayDyn
}  // namespace hxbit_ArrayProxyData

}  // namespace off
}  // namespace fmk
