#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <algorithm>
#include <cstdio>
#include <string>
#include <vector>
#include "paths.h"
#include "report.h"
namespace fmk {
void host_log(const char*, ...);
namespace {
struct File { std::wstring name; unsigned long long size, time; };
std::wstring dir(){ return data_dir(); }
bool info(const std::wstring&d,const std::wstring&n,File&f){WIN32_FILE_ATTRIBUTE_DATA a{};if(!GetFileAttributesExW((d+n).c_str(),GetFileExInfoStandard,&a))return false;f={n,((unsigned long long)a.nFileSizeHigh<<32)|a.nFileSizeLow,((unsigned long long)a.ftLastWriteTime.dwHighDateTime<<32)|a.ftLastWriteTime.dwLowDateTime};return true;}
std::vector<File> find(const std::wstring&d,const wchar_t*g){std::vector<File>v;WIN32_FIND_DATAW x{};HANDLE h=FindFirstFileW((d+g).c_str(),&x);if(h!=INVALID_HANDLE_VALUE){do{File f;if(!(x.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY)&&info(d,x.cFileName,f))v.push_back(f);}while(FindNextFileW(h,&x));FindClose(h);}std::sort(v.begin(),v.end(),[](const File&a,const File&b){return a.name<b.name;});return v;}
bool read(const std::wstring&p,std::string&s){HANDLE h=CreateFileW(p.c_str(),GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,nullptr,OPEN_EXISTING,0,nullptr);if(h==INVALID_HANDLE_VALUE)return false;LARGE_INTEGER z{};bool ok=GetFileSizeEx(h,&z)&&z.QuadPart<=67108864;if(ok){s.resize((size_t)z.QuadPart);DWORD n=0;ok=s.empty()||(ReadFile(h,s.data(),(DWORD)s.size(),&n,nullptr)&&n==s.size());}CloseHandle(h);return ok;}
void quote(std::string&o,const std::string&s){o+='"';for(unsigned char c:s){if(c=='\\')o+="\\\\";else if(c=='"')o+="\\\"";else if(c=='\r')o+="\\r";else if(c=='\n')o+="\\n";else if(c=='\t')o+="\\t";else o+=(char)c;}o+='"';}
bool write(const std::wstring&p,const std::string&s){auto t=p+L".tmp";HANDLE h=CreateFileW(t.c_str(),GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,0,nullptr);if(h==INVALID_HANDLE_VALUE)return false;DWORD n=0;bool ok=WriteFile(h,s.data(),(DWORD)s.size(),&n,nullptr)&&n==s.size()&&FlushFileBuffers(h);CloseHandle(h);if(ok)ok=MoveFileExW(t.c_str(),p.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH);if(!ok)DeleteFileW(t.c_str());return ok;}
}
void report_refresh(){
 auto d=dir(); auto inv=find(d,L"farever-inventory-*.json"); auto jobs=find(d,L"farever-jobs-*.json");File col{},atlas{};bool hc=info(d,L"farever-collection.json",col),ha=info(d,L"farever-atlas.tsv",atlas);
 unsigned long long sig=1469598103934665603ull;auto mix=[&](const File&f){sig^=f.size;sig*=1099511628211ull;sig^=f.time;sig*=1099511628211ull;};for(auto&f:inv)mix(f);for(auto&f:jobs)mix(f);if(hc)mix(col);if(ha)mix(atlas);static unsigned long long old=0;if(sig==old)return;
 SYSTEMTIME t{};GetLocalTime(&t);char date[32];sprintf_s(date,"%04u-%02u-%02u %02u:%02u:%02u",t.wYear,t.wMonth,t.wDay,t.wHour,t.wMinute,t.wSecond);
 std::string o="// Generated by farever-modkit.\r\nwindow.FAREVER_REPORT_DATA={generatedAt:\""+std::string(date)+"\",collection:",s;if(hc&&read(d+col.name,s))o+=s;else o+="null";
 auto array=[&](const char*k,const std::vector<File>&v){o+=","+std::string(k)+":[";bool first=true;for(auto&f:v){s.clear();if(!read(d+f.name,s))continue;if(!first)o+=',';o+=s;first=false;}o+=']';};array("inventories",inv);array("jobs",jobs);o+=",atlasTsv:";s.clear();if(ha&&read(d+atlas.name,s))quote(o,s);else o+="\"\"";o+="};\r\n";
 if(write(d+L"farever-report-data.js",o)){old=sig;host_log("report: dashboard data updated");}else host_log("report: dashboard write failed (%lu)",GetLastError());
}
}
